//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "generation", table_name = "systems")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub system: String,
    pub remark: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::measurements::Entity")]
    Measurements,
}

impl Related<super::measurements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Measurements.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
